spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  cache:
    type: redis
  batch:
    flush-interval-ms: 5000
  redis:
    node1:
      host: ${APP_REDIS_NODE1_HOST:localhost}
      port: 6379
    node2:
      host: ${APP_REDIS_NODE2_HOST:localhost}
      port: 6380
    node3:
      host: ${APP_REDIS_NODE3_HOST:localhost}
      port: 6381