version: '3.8'

services:
  # Cache Node 1
  redis1:
    image: redis:7-alpine
    container_name: typeahead_redis_1
    ports:
      - "6379:6379"

  # Cache Node 2
  redis2:
    image: redis:7-alpine
    container_name: typeahead_redis_2
    ports:
      - "6380:6379"

  # Cache Node 3
  redis3:
    image: redis:7-alpine
    container_name: typeahead_redis_3
    ports:
      - "6381:6379"

  app:
    build: .
    container_name: typeahead_server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-blue-salad-atdflx2w.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_Mp2PKcAvks4Z
      
      - APP_REDIS_NODE1_HOST=redis1
      - APP_REDIS_NODE2_HOST=redis2
      - APP_REDIS_NODE3_HOST=redis3
    depends_on:
      - redis1
      - redis2
      - redis3